name: Deploy to Production

on:
  push:
    branches:
      - main # Adjust branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Files to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "."  # Adjust the source path based on your project structure
          target: "/home/handokota/domains/twitterinstagram.handokota.com/public_html"  # Adjust the target path on the server
